INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (1, '43374');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (2, '"HP Trade"');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (3, '"Tarcher"');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (4, '[Atlanta, Ga.] : Audio Connoisseur');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (13, '1 7x');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (14, '1500 Books LLC');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (15, '1st Book Library');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (16, '1st World Library');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (17, '1st World Library - Literary Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (18, '1st World Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (19, '2.13.61');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (20, '2.13.61 Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (21, '21 Publishing Ltd');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (22, '21st Century Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (23, '2mpower');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (24, '3rd Woman Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (25, '498 Productions, LLC');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (26, '4th Estate, Limited');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (27, '5Continents');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (28, '826 Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (29, 'A & C Black (Childrens books)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (30, 'A Harvest Book  Harcourt, INC.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (31, 'A Harvest Book/Harcourt, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (32, 'A K PETERS');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (33, 'A King Production');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (34, 'A Shannon Ravenel Book');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (35, 'A Stepping Stone Book');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (36, 'A&b Publishers Group');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (37, 'A&C  Black');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (38, 'A&C Black');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (39, 'A. Michel');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (40, 'A. Mondadori');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (41, 'A. Niggli');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (42, 'A. R. E. Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (43, 'A.R.E. Press (Association of Research & Enlightenment)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (44, 'A2zpublications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (45, 'AA Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (46, 'AA World Services');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (47, 'AAAI Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (48, 'Aardvark Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (49, 'Aarhus Universitetsforlag');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (50, 'Abacus');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (51, 'Abacus (UK)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (52, 'Abacus Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (53, 'Abacus Books (London)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (54, 'Abbeville Kids');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (55, 'Abbeville Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (56, 'Abbey Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (57, 'ABC-CLIO');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (58, 'ABDO & Daughters');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (59, 'Abdo Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (60, 'Abdo Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (61, 'Aberdeen University Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (62, 'Aberjona Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (63, 'Abigon Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (64, 'Abingdon');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (65, 'Abingdon Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (66, 'Abjad Book Designers & Builders');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (67, 'Ablex Publishing Corporation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (68, 'Aboriginal Studies Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (69, 'About Comics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (70, 'Abradale Books/Harry N. Abrams');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (71, 'Abraham Guillen Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (72, 'ABRAMS');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (73, 'Abrams Books for Young Readers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (74, 'Absey & Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (75, 'Absolute Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (76, 'Abstract Studio');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (77, 'Abyss Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (78, 'Academic Foundation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (79, 'Academic Internet Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (80, 'Academic Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (81, 'Academica Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (82, 'Academy');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (83, 'Academy Chicago Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (84, 'Academy Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (85, 'Acadiensis Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (86, 'Acantilado');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (87, 'Acc Art Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (88, 'ACC Distribution');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (89, 'Access Ability Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (90, 'Accion Divulgativa Libros');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (91, 'Accord, a division of Andrews McMeel Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (92, 'Ace');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (93, 'Ace (The Berkley Publishing Group)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (94, 'Ace Book');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (95, 'Ace Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (96, 'Ace Books (NY)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (97, 'Ace Hardcover');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (98, 'Ace Trade');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (99, 'Ace/Berkley Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (100, 'ACMRS Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (101, 'ACMRS Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (102, 'Acorn Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (103, 'Acr Edition');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (104, 'Acrobat Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (105, 'Acropolis Books (GA)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (106, 'Acropolis Books (NY)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (107, 'ACTA Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (108, 'ACTA Universitatis Gothoburgensis');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (109, 'Actar');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (110, 'Actar D');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (111, 'Actes Sud');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (112, 'ACU Press/Leafwood Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (113, 'Adama Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (114, 'Adamant Media Corporation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (115, 'Adamantine Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (116, 'Adams Media');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (117, 'Adams Media Corporation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (118, 'Adamsking Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (119, 'Addicus Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (120, 'Addison Gallery of American Art');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (121, 'Addison Wesley');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (122, 'Addison Wesley Longman');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (123, 'Addison Wesley Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (124, 'Addison-Wesley');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (125, 'Addison-Wesley Professional');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (126, 'Adelphi');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (127, 'Adlard Coles Nautical');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (128, 'Adobe Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (129, 'Adonis & Abbey Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (130, 'Adrenaline Audiobooks');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (131, 'Adult');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (132, 'ADV Manga');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (133, 'Advanced Vivarium Systems');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (134, 'Advancement of Materials and Process Engineering');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (135, 'Advantage World Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (136, 'Advent Purple Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (137, 'Adventure Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (138, 'Adventures Unlimited Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (139, 'Aegypan');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (140, 'AEI Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (141, 'Aerie');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (142, 'Africa Research and Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (143, 'African American Images');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (144, 'Afton Historical Society Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (145, 'Agate B2');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (146, 'Agile Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (147, 'Agreka Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (148, 'Aguilar');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (149, 'Aguilar, Altea, Taurus, Alfaguara, S.A. de C.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (150, 'Aguilar, Altea, Taurus, Alfaguara, S.A. de C.V. (Mexico)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (151, 'Ah Ha Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (152, 'AHA! Process');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (153, 'Ahmadiyya Anjuman Ishaat');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (154, 'Ahmadiyya Anjuman Ishaat Islam');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (155, 'AIAA (American Institute of Aeronautics & Astronautics)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (156, 'AIT Planet Lar');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (157, 'AiT/Planet Lar');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (158, 'Ait/Planetlar');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (159, 'Aivia Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (160, 'AK Peters');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (161, 'AK Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (162, 'Akadine Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (163, 'Akal');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (164, 'Akal Ediciones');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (165, 'Akashic Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (166, 'Akashic Books/Punk Planet Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (167, 'Al Saadawi Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (168, 'Aladdin');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (169, 'Aladdin Paperbacks');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (170, 'Alamah');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (171, 'Alan Cohen Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (172, 'Alan Rodgers Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (173, 'Alan Sutton Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (174, 'Alan Wofsy Fine Arts');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (175, 'Alaska Native Language Center');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (176, 'Alaska Northwest Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (177, 'Alba');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (178, 'Alban Institute');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (179, 'Albany Institute of History and Art');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (182, 'Albert Whitman  Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (183, 'Albert Whitman & Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (184, 'Alberto Santos');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (185, 'Albin Michel');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (186, 'Albuquerque Museum');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (187, 'Albury Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (188, 'Alcoholics Anonymous World Services Inc');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (189, 'Alderac Entertainment Group');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (190, 'Alderac Entertainment Group (AEG)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (191, 'Aldrich Museum of Contemporary Art');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (192, 'Aletheia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (194, 'Alfaguara');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (195, 'Alfaguara Infantil');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (196, 'Alfaguara Juvenil');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (197, 'Alfaomega Grupo Editor');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (198, 'Alfred A Knopf');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (199, 'Alfred A. Knopf');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (200, 'Alfred A. Knopf Books for Young Readers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (201, 'Alfred A. Knopf Borzoi Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (202, 'Alfred A. Knopf, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (203, 'Alfred A. Knopf, Inc. (NY)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (204, 'Alfred A.Knopf');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (205, 'Alfred Music');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (206, 'Alfred Publishing Co.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (207, 'Alfred Publishing Co., Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (208, 'Alfred Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (209, 'ALGOL Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (210, 'Algonquin Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (211, 'Algonquin Books of Chapel Hill');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (212, 'Al-Hay(r)Ah Al-Miosraiyah Al- Aammah Lil-Kitaab');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (213, 'Alianza');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (214, 'Alianza Editorial');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (215, 'Alianza Editorial, S.A.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (216, 'Alias Enterprises');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (217, 'Alice James Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (218, 'Alice Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (219, 'Alien Perspective');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (220, 'Alienta');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (221, 'Alison Green Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (222, 'Alive Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (223, 'Allen  Unwin');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (224, 'Allen & Ulwin');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (225, 'Allen & Unwin');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (226, 'Allen & Unwin Academic');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (227, 'Allen & Unwin Australia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (228, 'Allen Lane');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (229, 'Allia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (230, 'Alliance Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (231, 'Allison & Busby');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (232, 'Allstar Marketing Group LLC');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (233, 'Allswell Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (234, 'Allworth');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (235, 'Allworth Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (236, 'Allyn & Bacon');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (237, 'ALM Media, LLC');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (238, 'Alma littera');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (239, 'Almqvist & Wiksell International');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (240, 'Alpha');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (241, 'Alpha Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (242, 'Alpha Connections');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (243, 'Alpha Multimedia, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (245, 'Altamira Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (246, 'Alternative Comics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (247, 'Alyson Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (248, 'AM Editores');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (249, 'AMACOM');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (250, 'AMACOM/American Management Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (251, 'Amadeus');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (252, 'Amadeus Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (253, 'Amal Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (254, 'Amana Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (255, 'Amat');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (256, 'Amazing Facts');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (257, 'Amazon Digital Services');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (258, 'Amazon Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (259, 'AmazonEncore');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (260, 'Ambassador House');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (261, 'Ambassador-Emerald International');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (262, 'Amber-Allen Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (263, 'Amer. Soc.of Agricultural Eng');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (264, 'Amereon');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (265, 'Amereon Limited');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (266, 'America Star Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (267, 'American Academy of Pediatrics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (268, 'American Association for Clinical Chemistry, Incorporated');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (269, 'American Association for State and Local History');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (270, 'American Association of Retired Persons');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (271, 'American Association of School Administrators');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (272, 'American Audio Prose Library');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (273, 'American Bar Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (274, 'American Birding Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (275, 'American Cancer Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (276, 'American Chemical Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (277, 'American Correctional Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (278, 'American Counseling Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (279, 'American Diabetes Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (280, 'American Dietetic Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (281, 'American Fantasy');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (282, 'American Geophysical Union');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (283, 'American Girl Publishing Inc');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (284, 'American Historical Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (285, 'American Homestyle and Gardening/Gruner+jahr USA Pub');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (286, 'American Institute of Chemical Engineers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (287, 'American Institute of Physics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (288, 'American Library Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (289, 'American Life Foundation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (290, 'American Mathematical Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (291, 'American Mathematical Society(RI)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (292, 'American Media (CA)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (293, 'American Media Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (294, 'American Medical Association Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (295, 'American Nurses Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (296, 'American Phytopathological Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (297, 'American Planning Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (298, 'American Political Biography Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (299, 'American Psychiatric Association Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (300, 'American Psychiatric Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (301, 'American Psychological Association (APA)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (302, 'American Public Health Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (303, 'American Quilter's Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (304, 'American Red Cross');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (305, 'American Registry of Pathology');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (306, 'American Renaissance for the Twenty-First Century');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (307, 'American Reprint Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (308, 'American School of Classical Studies');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (309, 'American Society for Training & Development');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (310, 'American Society of Civil Engineers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (311, 'American Society of Heating Refrigerating and Air-Conditioning Engineers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (312, 'American Society of Mechanical Engineers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (313, 'American Society of Papyrologists');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (314, 'American Trust Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (315, 'American University in Cairo Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (316, 'American Water Works Association');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (317, 'American-Israeli Cooperative Enterprise');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (318, 'America's Best Comics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (319, 'America's Test Kitchen');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (320, 'Amerisearch');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (321, 'AMG Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (322, 'Amherst Media');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (323, 'Amherst Media, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (324, 'Amistad');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (325, 'Amistad Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (326, 'Ammo Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (327, 'Amon Carter Museum');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (328, 'Amorata Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (329, 'Amos Hobby');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (330, 'Ampersand Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (331, 'Amphoto Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (332, 'AMR/Advanced Management Reports');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (333, 'AMS Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (334, 'Amsco Music');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (335, 'Amsterdam University Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (336, 'Anagrama');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (337, 'Anaya');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (338, 'Anaya & Mario Muchnik');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (339, 'Anaya Multimedia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (340, 'Anaya Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (341, 'Ancestry.com');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (342, 'Anchor');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (343, 'Anchor Bible');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (344, 'Anchor Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (345, 'Anchor Books/Knopf Doubleday Publishing Group');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (346, 'Anchor Canada');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (347, 'Ancient City Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (348, 'And Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (349, 'Andersen');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (350, 'Andersen Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (351, 'Andersen Press Ltd');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (352, 'Anderson Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (353, 'Andre Deutsch');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (354, 'Andre Deutsch Ltd');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (355, 'Andrea Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (356, 'Andreas Papadakis Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (357, 'Andrew Brodie Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (358, 'Andrew Mowbray Incorporated, Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (359, 'Andrews and McMeel');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (360, 'Andrews McMeel Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (361, 'Andrews McMeel Publishing, LLC');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (362, 'Andrews University Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (363, 'Andy Kilpatrick Publishing Empire');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (364, 'Angel Bea Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (365, 'Angel Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (366, 'Angel City Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (367, 'Angela Royal Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (368, 'Anglo-Norman Text Society');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (369, 'Anglo-Saxon Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (370, 'Angriff Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (371, 'Anker Publishing Company, Incorporated');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (372, 'Ann Arbor Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (373, 'Anness Publishing/Southwater Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (374, 'Annick Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (375, 'Annie's');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (376, 'Annual Reviews');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (377, 'Anomalist Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (378, 'Another Chicago Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (379, 'Anova Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (380, 'Anova Children's Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (381, 'Ansel Adams');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (382, 'Antarctic Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (383, 'Anthem Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (384, 'Anthony D'Offay Gallery');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (385, 'Anthony Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (386, 'Antique Trader Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (387, 'Anvil Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (388, 'Anvil Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (389, 'Anvil Press Poetry');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (390, 'APA Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (391, 'Aperture');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (392, 'Apex Venture Advisors');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (393, 'Aphrodisia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (394, 'Apocryphile Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (395, 'Apollos');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (396, 'Appa the Association of Higher Education Facilities');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (397, 'Appalachian Mountain Club');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (398, 'Appalachian Mountain Club Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (399, 'Applause Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (400, 'Applause Theatre & Cinema Book Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (401, 'Apple');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (402, 'Apple Paperbacks (Scholastic)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (403, 'Appledore Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (404, 'Applewood Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (405, 'Apress');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (406, 'Aqua Quest Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (407, 'Arab Image Foundation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (408, 'Arabesque');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (409, 'Arbordale Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (410, 'Arcade Pub');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (411, 'Arcade Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (412, 'Arcade Publishing (NYC)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (413, 'Arcadia Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (414, 'Arcadia Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (415, 'Arcadia Publishing (SC)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (416, 'Arcadia-Clark');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (417, 'Archaia');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (418, 'Archer Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (419, 'Archer Editions Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (420, 'Archie Comics');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (421, 'Archipelago Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (422, 'Archipelago Publishing (WA)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (423, 'Architectural Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (424, 'Archon Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (425, 'Archway Paperbacks');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (426, 'ARCO');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (427, 'Arcturus');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (428, 'Ardis Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (429, 'Arena');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (431, 'Ariadne Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (432, 'Ariel Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (433, 'Arima Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (434, 'Aris & Phillips');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (435, 'Aris and Phillips');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (436, 'Arizona Center for Medieval and Renaissance Studies (ACMRS)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (437, 'Arizona Highways Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (438, 'Arkana');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (439, 'Arkana Paperbacks');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (440, 'Arkana/Penguin');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (441, 'Arkano Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (442, 'Arkeoloji Ve Sanat Yayinlari');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (443, 'Arkham House Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (445, 'Arlen House');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (446, 'Arlington House');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (447, 'Armada');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (448, 'Armchair Detective Library');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (449, 'Arms & Armour Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (450, 'Arno');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (451, 'Arno Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (452, 'Arnoldo Mondadori');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (453, 'Arnoldsche Verlagsanstalt GmbH');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (454, 'Arrow');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (455, 'Arrow (A Division of Random House Group)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (456, 'Arrow Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (457, 'Arrow Books Ltd');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (458, 'Arrow Map');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (459, 'Arrow Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (460, 'Arsenal Pulp Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (461, 'Art Direction Book Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (462, 'Art Enterprise');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (463, 'Art Gallery of York University/The Power Plant');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (464, 'Art Institute of Chicago');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (465, 'Art Media Resources');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (466, 'Arte Publico Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (467, 'Artech House Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (468, 'Arthritis Foundation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (469, 'Arthur A. Levine');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (470, 'Arthur A. Levine Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (471, 'Arthur A. Levine Books / Scholastic Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (472, 'Article 19');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (473, 'Artisan');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (474, 'Artisan Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (475, 'Artistpro.com');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (476, 'Artist's and Photographers' Press Ltd');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (477, 'Arts Publications');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (478, 'Artspace Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (479, 'ASCD');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (480, 'Ascend Beyond Pub.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (482, 'Ash Tree Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (483, 'Ashfield Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (484, 'Ashgate Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (485, 'Ashley Mark Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (486, 'Ashley Mark Publishing Company');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (487, 'Ashleywilde, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (488, 'Ash-Tree Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (489, 'ASK Productions');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (490, 'Aslan Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (491, 'ASM Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (492, 'ASM Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (493, 'Asogomi Publishing International');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (494, 'Aspasia Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (495, 'Aspatore Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (496, 'Aspect');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (497, 'Aspect Fantasy');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (498, 'Aspen Publishers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (499, 'Aspen Systems Corporation');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (500, 'ASQ Quality Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (501, 'Associated');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (502, 'Associated Music Publishers, Inc.');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (503, 'Association for Scottish Literary Studies');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (504, 'Association for Supervision & Curriculum Development');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (505, 'Association of Official Analytical Chemist');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (506, 'Association of Waldorf Schools of North America Publications (Answa)');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (507, 'Assouline');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (508, 'Assouline Publishing');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (509, 'As-Sunna Foundation of America');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (510, 'AST');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (511, 'Asterix');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (512, 'ASTM International');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (513, 'Astrolog Publishing House');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (515, 'Atelos');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (516, 'Atelos Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (517, 'Athena University Press');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (518, 'Atheneum');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (519, 'Atheneum Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (520, 'Atheneum Books for Young Readers');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (521, 'Atheneum Books for Young Readers: Richard Jackson Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (522, 'Atheneum/Richard Jackson Books');
INSERT INTO inventario_editorial (id_editorial, editorial) VALUES (523, 'Athlone Press');
